on:
  push:
    branches:
      - master
name: Publish
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Ancient Version of Hugo
        run: |
          curl -sLO https://github.com/spf13/hugo/releases/download/v0.14/hugo_0.14_linux_amd64.tar.gz
          tar zxvf hugo_0.14_linux_amd64.tar.gz
      - name: Build Site
        run: |
          hugo_0.14_linux_amd64/hugo_0.14_linux_amd64 -s .
          ls -l public

